//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharp2048.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genome
    {
        public System.Guid GenomeIdentifier { get; set; }
        public string GenomeXml { get; set; }
        public string Description { get; set; }
    }
}
